packages:
  - apps/*
  - packages/*
  - tools/*
  - apps/apps/*

catalogMode: prefer

catalog:
  "@better-auth/drizzle-adapter": ^1.6.23
  "@tailwindcss/vite": ^4.3.2
  "@types/node": ^24
  "@types/pg": ^8.20.0
  better-auth: ^1.6.23
  dotenv: ^17.4.2
  drizzle-kit: 1.0.0-rc.4
  drizzle-orm: 1.0.0-rc.4
  pg: ^8.22.0
  tailwindcss: ^4.3.2
  tsx: ^4.23.0
  typescript: ^5.9.3
  valibot: ^1.4.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - hono@4.12.30
allowBuilds:
  esbuild: true
